### ISSUE TITLE
Introduce Multiversion support

### ISSUE THREAD

**Issue by yannicklamprecht** [yannicklamprecht/WorldBorderAPI#12]
Refactor the project to add multiversion support.
Material for discussion:
- Kotlin instead of Java
- which versions should be supported?
  - [ ] 1.8.8- 1.14
  - [ ] 1.12.2-1.14

**Comment by xist** [comment]
All the versions :)

**Comment by yannicklamprecht** [comment]
The default Minecraft worldborder is not available below 1.8 so all the versions is not possible.

**Comment by xist** [comment]
Added some versions in the latest fork, I can think of simpler ways to do it (maybe we reflect). But for now it's better than no support. 🤔

**Comment by xist** [comment]
Tested on 1.8.8 and 1.13 as well (ill try more later).

**Comment by yannicklamprecht** [comment]
Reflection is a no go for that project. I will introduce a better abstraction layer some day.
