### ISSUE TITLE
Have the green/moving effect when using the timed method in API

### ISSUE THREAD

**Issue by opd02** [yannicklamprecht/WorldBorderAPI#132]
**Is your feature request related to a problem? Please describe.**
I think if would be great to get the green-moving world border if you use the WorldBorderAPI#setBorder(Player player, double size, int time, TimeUnit timeUnit); method in the API. Currently, the WB just disappears and after the set amount of time, it reappears at the new size.

**Describe the solution you'd like**
I was the size changing of the world border to look like it does when you use the /worldborder command and specify a time.

**Describe alternatives you've considered**
This may not be possible. I am not great with NMS.

**Comment by yannicklamprecht** [comment]
I'll look into it when I've time again. 
Could you please attach the use code as a snippet.

**Comment by opd02** [comment]
Yah definitely! I was using this...
`for (Player player : Bukkit.getServer().getOnlinePlayers()) {
                    GambitRemastered.worldBorderApi.setBorder(player, 500, 10, TimeUnit.SECONDS);
                }`
to try and loop through the players and update their worldborders to expand to a size of 500 block in 10 seconds smoothly. Currently the world border vanishes and reappears in 10 seconds at the new size.

I'll also try and mess around with it (when I also have time) and if I get the green moving effect, I'll make a pull request.

But thank you for the great repository! It adds such a cool effect for my minigame!
