### ISSUE TITLE
Time argument is not working as intended

### ISSUE THREAD

**Issue by dndrbots** [yannicklamprecht/WorldBorderAPI#17]
**Describe the bug**
Border changes instantly instead of moving slowly for the period of time

**To Reproduce**
`this.plugin.worldBorderApi.setBorder(player, radius, time);`
I am using this function like in your plugin example, but border instantly moves to the radius I need

**Expected behavior**
Border should move slowly towards the player / desired location

**Screenshots**
Nope

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Spigot version: 1.8
 - Minecraft version: 1.8 / 1.8.9

**Comment by dndrbots** [comment]
I can record a video showing this issue

**Comment by yannicklamprecht** [comment]
Will look at it later. It's 11am here.

**Comment by yannicklamprecht** [comment]
Looks like the rnumWorldBorderaction needs to be adjusted in version 1.8.8. I'll fix that this evening CET.

**Comment by yannicklamprecht** [comment]
@dndrbots what timeUnit did you use?   Time is not second it is millisecond.

**Comment by yannicklamprecht** [comment]
fixed in https://github.com/yannicklamprecht/WorldBorderAPI/commit/2aeb0aeb7e10ea22e5f74e948405cd3e8155cfbe

**Comment by dndrbots** [comment]
Gotta check, thanks in advance! <3

**Comment by dndrbots** [comment]
I thought that the time variable is how long will the border travel from starting location to the size you need. But looks like it is used for scheduling border change. Is there like any way that you can shrink it smoothly?

**Comment by yannicklamprecht** [comment]
Not in 1.8. probably in later versions that will work.
