### ISSUE TITLE
Classes of this?

### ISSUE THREAD

**Issue by ObeyBeastJj23** [yannicklamprecht/WorldBorderAPI#18]
What's the class i should import if i wanted to?
like org.worldborderapi.WorldBorderAPI?

**Comment by dndrbots** [comment]
```
import com.github.yannicklamprecht.worldborder.api.BorderAPI;
import com.github.yannicklamprecht.worldborder.api.WorldBorderApi;

private WorldBorderApi worldBorderApi = BorderAPI.getApi();
```

And then you can use `worldBorderApi` as you like to.
For example, `worldBorderApi.resetWorldBorderToGlobal();`

Hope that helps
