### ISSUE TITLE
getSize() of player

### ISSUE THREAD

**Issue by 360matt** [yannicklamprecht/WorldBorderAPI#26]
In the API:

``BorderAPI.getApi().getWorldBorder((Player) sender).getSize()`` return the same value of GlobalWorldBorder, but I have changed the worldBorder of the player (me) to 16x16 blocs (1 chunk).

I can't reset because I must to check if the WorldBorder have been changed before when I create a switch command on/off

**Comment by yannicklamprecht** [comment]
Feature will be added with #25 

Currently player based borders aren't persisted. You need to keep the info yourself
