### ISSUE TITLE
Elsewhere

### ISSUE THREAD

**Issue by GameChampCrafted** [yannicklamprecht/WorldBorderAPI#31]
How exactly do I set the border onjoinevent and out of other classes?

**Comment by yannicklamprecht** [comment]
There are two examples here:
https://github.com/yannicklamprecht/WorldBorderAPI/blob/master/WorldBorderAPITestPlugin/src/main/java/com/github/yannicklamprecht/worldborder/testplugin/BorderTestCommands.java

https://github.com/yannicklamprecht/WorldBorderAPI/blob/master/WorldBorderAPITestPlugin/src/main/java/com/github/yannicklamprecht/worldborder/testplugin/WorldBorderTestPlugin.java#L40-L53

The persistent stuff can be ignored if you do not need that.
