### ISSUE TITLE
Remove outside border tint 

### ISSUE THREAD

**Issue by Dyamont** [yannicklamprecht/WorldBorderAPI#32]
Hi, there is any way to remove red tint outside the border? Setting warning blocks to zero works, but it only removes tint inside the border.

**Comment by yannicklamprecht** [comment]
Not that I know since it's a client side effect. You just can try to set a negative warning blocks size. The other way would be to just remove the border if the player is outside.

**Comment by Dyamont** [comment]
I tried to set a negative warning blocks size but it also doesn't work properly. I wanna create something like players regions so I can't remove it.

**Comment by yannicklamprecht** [comment]
> I tried to set a negative warning blocks size but it also doesn't work properly. I wanna create something like players regions so I can't remove it.

Look a how the BentoBox Add-on did it. https://github.com/BentoBoxWorld/Border/
They used the border to show island borders.
