### ISSUE TITLE
Pre 1.16 compatibility

### ISSUE THREAD

**Issue by sgdc3** [yannicklamprecht/WorldBorderAPI#33]
https://github.com/yannicklamprecht/WorldBorderAPI/blob/4b4426af5e7dbbe2bf82918c8d58bb7e72ce481a/WorldBorderPlugin/src/main/resources/plugin.yml#L4

This breaks pre 1.16 compatibility

**Comment by yannicklamprecht** [comment]
https://github.com/yannicklamprecht/WorldBorderAPI/releases/tag/1.161.3
