### ISSUE TITLE
1.9 / 1.12.2 support

### ISSUE THREAD

**Issue by Dutchwilco** [yannicklamprecht/WorldBorderAPI#38]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
also support for 1.9 till 1.12.2 

**Describe alternatives you've considered**
x

**Additional context**
Good guy!!!

**Comment by yannicklamprecht** [comment]
See old version:

Unsupported but working release:
- 1.8.8, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14.4, 1.15.2:
https://github.com/yannicklamprecht/WorldBorderAPI/releases/tag/1.15.2
