### ISSUE TITLE
Maven repo for 1.170.0 is not available

### ISSUE THREAD

**Issue by tastybento** [yannicklamprecht/WorldBorderAPI#44]
**Describe the bug**
I'm trying to link to 1.170.0 via Maven but it's not available on jitpack or the other repo you have in readme. It looks like Gradle is still building using 1.8 JVM so there's an error. See https://jitpack.io/com/github/yannicklamprecht/WorldBorderAPI/1.170.0/build.log

**To Reproduce**
1. Use 1.170.0 in dependency section of POM

```
        <dependency>
            <groupId>com.github.yannicklamprecht.WorldBorderAPI</groupId>
            <artifactId>API</artifactId>
            <version>1.170.0</version>
        </dependency>
```

**Expected behavior**
Compile without error.

**Comment by yannicklamprecht** [comment]
https://github.com/yannicklamprecht/WorldBorderAPI#how-to-add-with-maven

Moved to a reliable repository. JitPack cannot build more complex Gradle projects or Gradle projects at all.
