### ISSUE TITLE
paper updated a thing and now wants us to complain to you, here i am

### ISSUE THREAD

**Issue by mrfloris** [yannicklamprecht/WorldBorderAPI#46]
```
> [STDOUT] Version: v1_17_r1
> [17:26:47 WARN]: Nag author(s): '[]' of 'WorldBorderAPI' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

> ver
[17:57:19 INFO]: Checking version, please wait...
[17:57:19 INFO]: This server is running Paper version git-Paper-151 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa)
You are running the latest version
Previous version: git-Paper-146 (MC: 1.17.1)
>

> ver WorldBorderAPI
[17:58:20 INFO]: WorldBorderAPI version 1.170.0
>
```

**Comment by yannicklamprecht** [comment]
Thanks, debug logging that I forgot to convert. ❤️ 
`
        System.out.println("Version: " + version);
        WorldBorderApi worldBorderApi;
        switch (version) {
            case "v1_16_r3" -> worldBorderApi = new com.github.yannicklamprecht.worldborder.v1_16.Border();
            case "v1_17_r1" -> worldBorderApi = new com.github.yannicklamprecht.worldborder.v1_17.Border();
            default -> {
                getLogger().info("Unsupported version of Minecraft");
                Bukkit.getPluginManager().disablePlugin(this);
                return;
            }
        }
`

The only two logs I've and one is flawed. 😆

**Comment by yannicklamprecht** [comment]
Should be fixed in https://github.com/yannicklamprecht/WorldBorderAPI/releases/tag/1.171.0
