### ISSUE TITLE
Method .setBorder() doesn't work

### ISSUE THREAD

**Issue by Endxxr** [yannicklamprecht/WorldBorderAPI#54]
**Describe the bug**
The method `.setBorder()` doesn't create a border. No Errors appear.

**To Reproduce**
Use the `setBorder(Player player, Double size, Location location)` method

**Expected behavior**
A border should appear

**Screenshots**
Gist: https://gist.github.com/EnderF5027/1cc283e02b08caf6ddae93a08aae5828 [Line: 90]

**Desktop (please complete the following information):**
 - OS: Windows 11 Last Version
 - IDE: IntelliJ Idea 
 - Server: Paper 1.17.1 (Test Server)

Probably Im doing a stupid mistake, but im here to learn.

**Comment by EnderF5027** [comment]
Im pretty dumb and didnt realized that the API were sending the packets before the player joins

**Comment by mattsegura** [comment]
I'm running into the same issue you had here, I know it's been a while but what was the fix?

**Comment by Endxxr** [comment]
> I'm running into the same issue you had here, I know it's been a while but what was the fix? 

You have to set the border 1 tick later. If you want to be sure, you can do it 3-4 ticks later too. You have to use the Bukkit Scheduler for do this
