### ISSUE TITLE
Border doesnt damaging

### ISSUE THREAD

**Issue by UsainSrht** [yannicklamprecht/WorldBorderAPI#59]
**Describe the bug**
Client side border doesn't give damage when you're outside.

**To Reproduce**
1. set a client side world border for player
2. get the player's world border
3. modify it with using setDamagePerSecondPerBlock and lerp
4. send the modified world border to the player
5. you don't take d amage when you're outside :(

**Expected behavior**
I expect taking damage when i'm outside of the border

**Screenshots**

https://user-images.githubusercontent.com/59025999/143779312-67e1410a-309e-4221-b139-858f9e33dace.mp4

**Additional context**
Also I'm checking the settings are applied. getDamagePerSecondPerBlock() returning what i wrote.

**Comment by yannicklamprecht** [comment]
It is only a packet based border. It will never deal any damage.
I'll deprecate a remove that method in future.

**Comment by UsainSrht** [comment]
> It is only a packet based border. It will never deal any damage. I'll deprecate a remove that method in future.

Okay. But ı've tried to give damage manually but isInBorder method isn't working as it should.
It returns true when player doesn't have client side border. It returns false when player has. No matter player is inside or outside if player has client side world border it return false. Can you check it pls?

**Comment by yannicklamprecht** [comment]
> > It is only a packet based border. It will never deal any damage. I'll deprecate a remove that method in future.
> 
> Okay. But ı've tried to give damage manually but isInBorder method isn't working as it should. It returns true when player doesn't have client side border. It returns false when player has. No matter player is inside or outside if player has client side world border it return false. Can you check it pls?

Will fix it this evening.
You see the bug? https://github.com/yannicklamprecht/WorldBorderAPI/blob/main/src/main/java/com/github/yannicklamprecht/worldborder/impl/WorldBorder.java#L48 🙄
