### ISSUE TITLE
update maven repo

### ISSUE THREAD

**Issue by ooehme** [yannicklamprecht/WorldBorderAPI#64]
Please add 1.18 version to your https://eldonexus.de/ repo :) Big thnx! Great work!

**Comment by yannicklamprecht** [comment]
It is https://eldonexus.de/#browse/browse:maven-snapshots:com%2Fgithub%2Fyannicklamprecht%2Fworldborderapi%2F1.18.0--SNAPSHOT

Use the snapshot for now.

**Comment by yannicklamprecht** [comment]
Is fixed now. https://eldonexus.de/#browse/browse:maven-releases:com%2Fgithub%2Fyannicklamprecht%2Fworldborderapi%2F1.180.0

Readme is updated as well.
