### ISSUE TITLE
Release without jar files?

### ISSUE THREAD

**Issue by mrfloris** [yannicklamprecht/WorldBorderAPI#67]
Hey there, not sure how to contact you, my apologies if this isn't the way. 

I noticed (compared to previous releases) that the 1.18.1 release came without the jar files. Is this intentional or did a release-build go wrong?

https://github.com/yannicklamprecht/WorldBorderAPI/releases/tag/1.18.1

**Comment by yannicklamprecht** [comment]
Thanks, it's the right way.  Yeah failed, need to re activate artifact upload on release.
Sorry for being late was sunken deeply into No Man's Sky.
