### ISSUE TITLE
Can't compile after following how-to-use

### ISSUE THREAD

**Issue by Zorua162** [yannicklamprecht/WorldBorderAPI#73]
**Describe the bug**
On following https://github.com/yannicklamprecht/WorldBorderAPI/blob/main/how-to-use.md my code cannot compile
**To Reproduce**
1. Add maven dependency to pom.xml
2. Add dependency to plugin.yml
3. Add example code
4. Compile code
5. See error

**Expected behavior**
Code should compile
**Screenshots**
Compilation error log:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/zorua/Documents/IdeaProjects/HeightBorder/src/main/java/me/zorua162/heightborder/HeightBorder.java:[3,51] cannot access com.github.yannicklamprecht.worldborder.api.WorldBorderApi
  bad class file: C:\Users\zorua\.m2\repository\com\github\yannicklamprecht\worldborderapi\1.180.0\worldborderapi-1.180.0.jar(/com/github/yannicklamprecht/worldborder/api/WorldBorderApi.class)
    class file has wrong version 61.0, should be 59.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /C:/Users/zorua/Documents/IdeaProjects/HeightBorder/src/main/java/me/zorua162/heightborder/HeightBorder.java:[40,12] cannot find symbol
  symbol:   class WorldBorderApi
  location: class me.zorua162.heightborder.HeightBorder
[ERROR] /C:/Users/zorua/Documents/IdeaProjects/HeightBorder/src/main/java/me/zorua162/heightborder/HeightBorder.java:[53,35] cannot find symbol
  symbol:   class WorldBorderApi
  location: class me.zorua162.heightborder.HeightBorder
[ERROR] /C:/Users/zorua/Documents/IdeaProjects/HeightBorder/src/main/java/me/zorua162/heightborder/HeightBorder.java:[53,142] cannot find symbol
  symbol:   class WorldBorderApi
  location: class me.zorua162.heightborder.HeightBorder
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
```
Full code here: 
https://github.com/Zorua162/HeightBorder/tree/world-border-warning

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ Idea 
 - Version 2020.3.1

**Additional context**
I am a really new java programmer, just trying to figure out a small plugin as a personal project, sorry in advance if this is the wrong way to report this/ if I'm doing something really wrong, I've tried to search the issue as best I can, but being so new to Java I'm struggling to know exactly what to search.
Please let me know of any mistakes I have made in reporting this and I will try to rectify them or not make them in future.

My best guess is that this isn't an issue with your api, but instead with your how-to-use (or with my understanding of it), specifically
something related to the version as per the error saying `has wrong version 61.0, should be 59.0`.

**Comment by yannicklamprecht** [comment]
Upgrade to Java 17. You are trying to compile it with Java 15.

**Comment by Zorua162** [comment]
Really sorry, I assumed I had checked that, but hadn't. Thanks so much for the help!
