### ISSUE TITLE
WorldBorder doesn't appear around islands (BSkyBlock - BentoBox | Border)

### ISSUE THREAD

**Issue by spencer-wild** [yannicklamprecht/WorldBorderAPI#75]
**Describe the bug**
Vanilla WorldBorder is supposed to appear around the player's islands in BSkyBlock (By BentoBox), however instead there are [Warn] and [Error] in the console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install purpur, then install BentoBox with BSkyBlock with the border addon (my setup includes these other addons to BentoBox: Biomes, Challenges, ControlPanel, DimensionalTrees, Level, Limits, Warps).
2. Install WorldBorderAPI plugin.
3. Configure the border plugin to use WorldBorderAPI to display the border, and have it on by default (see config attached bia pastebin below)
4. Log into the server and create any island using the (/is create) command. 
5. Teleport to island via (/is go). First error will appear when you get there, and no border will appear.
6. Try to enable/disable border using (/is border). An error will occur and no border will appear.

**Expected behaviour**
Vanilla WorldBorder would appear around the island. 

**Actual behaviour**
It doesn't an error occurs in the console. Running the '/island border' command to enable/disable the island border also causes an error to appear in the console.

This error appears when you first teleport to the island: https://pastebin.com/ytD3A1Ga

This error appears when you run '/island border': https://pastebin.com/GeBisDDz

Configuration for border plugin of bskyblock: https://pastebin.com/96spWgQy

At no point is there a border visibly present. 

**Screenshots**
n/a

**MC Version**
Current: git-Purpur-1544 (MC: 1.18.1)
Version of bentobox: 1.19.0

**Additional context**
I tried using both the latest snapshot of WorldBorderAPI and the stable release for 1.18.1, both result in an error.

I wasn't sure if this was a problem for the people who created the border addon or BentoBox, but in their support Discord they stated  this was a problem with the code of worldborderapi, and that I needed to create a ticket here.

If any additional info is needed let me know.

**Comment by yannicklamprecht** [comment]
Wrong jar used. Use the one not suffixed with -dev.
