### ISSUE TITLE
Can't work out how to import your API to gradle

### ISSUE THREAD

**Issue by UntouchedOdin0** [yannicklamprecht/WorldBorderAPI#76]
I've tried the different maven repositories you've mentioned to get the api but I can't work out how to to correctly import the API. This api would be perfect for what I want it to do but if I can't get it to import then that makes it much harder is there any way you could possibly put it on somewhere like jitpack.io where it's far easier for developers to get to?

**Comment by yannicklamprecht** [comment]
https://github.com/yannicklamprecht/WorldBorderAPI/blob/main/how-to-use.md

See gradle section at the bottom.

**Comment by UntouchedOdin0** [comment]
I followed those instructions, it seems to find it fine but I can't use any of the methods in the code?

**Comment by UntouchedOdin0** [comment]
I think this is an issue your end on your maven server?
