### ISSUE TITLE
Lower the target Java version down to 1.8

### ISSUE THREAD

**Issue by UntouchedOdin0** [yannicklamprecht/WorldBorderAPI#77]
Please change the target Java version down to 1.8 so more people can use your API. You don't let plugins which support 1.8-1.18 use your plugin.

**Comment by yannicklamprecht** [comment]
As mentioned in spigotmc private chat:

I will not drop the tooling for that, just to get back to an ancient version. Feel free to use the API dependency of the version 1.16.5. The API itself didn't change so it should be perfectly compatible with each new implementation.

Version 1.16.5 plugin implementation is compatible from 1.8.8 - 1.16.5.
