### ISSUE TITLE
Problems with implementing dependency in Maven

### ISSUE THREAD

**Issue by VerleneDodds** [yannicklamprecht/WorldBorderAPI#86]
Hello, I am trying to implement the WorldBorderAPI in my spigot plugin, and it's continuing to say "Dependency 'com.github.yannicklamprecht:worldborderapi:1.180.0' not found " could somebody take a look at my pom file and tell me if I've done something wrong? (Snippet of pom below, whole file also uploaded)

`    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
        <id>eldonexus</id>
        <url>https://eldonexus.de/repository/maven-releases/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.18.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.yannicklamprecht</groupId>
            <artifactId>worldborderapi</artifactId>
            <version>1.180.0</version>
        </dependency>
    </dependencies> `
[pom.txt](https://github.com/yannicklamprecht/WorldBorderAPI/files/8936052/pom.txt)

**Comment by yannicklamprecht** [comment]
You need to use at least Java 17. Java 8 doesn't work.

**Comment by VerleneDodds** [comment]
Even with changing that java version it is still giving me the dependency not found error, do you have any other suggestions?

**Comment by alekso56** [comment]
You are using the wrong version use this with minecraft 1.18.2

```
<dependency>
  <groupId>com.github.yannicklamprecht</groupId>
  <artifactId>worldborderapi</artifactId>
  <version>1.182.0</version>
</dependency>
```

**Comment by VerleneDodds** [comment]
yeah, I tried that one also, and am still having the same problem, I truly have zero clue what could be going on with it.
