### ISSUE TITLE
Update API to 1.19-R0.1

### ISSUE THREAD

**Issue by ukeo** [yannicklamprecht/WorldBorderAPI#88]
Can you please update the api to 1.19? Thank you

**Comment by yannicklamprecht** [comment]
Please use:

Player#[getWorldBorder](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getWorldBorder())()
Player#[setWorldBorder](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setWorldBorder(org.bukkit.WorldBorder))(worldborder)
Server#[createWorldBorder](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#createWorldBorder())()

[https://hub.spigotmc.org/stash/proj...mits/62845f2fd8651978e4f1151297e00ed9bcccf938](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/62845f2fd8651978e4f1151297e00ed9bcccf938)

[https://hub.spigotmc.org/stash/proj...mits/6c308e1b57e44bc97a0743b4e9703ed5469e09dd](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6c308e1b57e44bc97a0743b4e9703ed5469e09dd)

**Comment by edrian09** [comment]
can you help me to update it to 1.19?

**Comment by yannicklamprecht** [comment]
> can you help me to update it to 1.19?

It is already. Would recommend to use the above methods instead.
